### ISSUE TITLE
Duplicate Timestamp Entries

### ISSUE THREAD

**Issue by EdwardTheGreat** [mikepotjer/vfp-git-utils#4] opened 2016-04-12 20:13 UTC
When I push files to the repository, I noticed that **some of the files have their timestamp reverted back even though the file contents have changed.** I repeated editing the file, running BinaryToTextRepo several times with consistent results. 

**I discovered that the files in question had duplicate entries in the .gittimestamp.  Sometimes the duplicates had the same datetime and sometimes they were different.** (See the example from the .gittimestamp file at end of this message).  I haven't figured out what causes that.  

I have a slight suspicion that it may have to do with upper/lower case of the file extensions, but there is only minor evidence for this.  The evidence is that when i edit the form in foxpro, it saves with an upper case extension, and when it reverts the file, it changes it to lower case.

Another possible cause for the duplicate entry in timestamp file is my environment.
I mostly use thor_proc_gitutilities to do everything related to the repositories.  I occasionally use tortoiseget, usually to manage conflicts in versions.  I doubt this has anything to do with the problem, but include it for completeness.

So I don't know what causes the duplicate timestamps, **here is what I believe causes it to revert the timestamp on files that have been modified.**
BinaryToTextRepo calls CleanupVFPBinaries which calls RestoreRepoTimestamps.
**RestoreRepoTimestamps** has a cursor of files changed since commit.
It creates an array from the .gttimestamp file.
It goes thru each file in the cursor and looks for the **First** matching entry in the timestamp array.
If found, it **deletes this First entry from the array, but leaves the duplicates in it.**
Then it goes back thru the entire array, and modifies the datetime of any file in the array that does not match the datetime of the file on disk.

Deleting the duplicates from the file solved the issue of it reverting timestamps of files that had changed, but it would be nice if the program handled duplicates on its own.

Thank you for your Wonderful program.

Eddie Caldwell

2016-03-24T12:04:06 shiprecv.mn2   && different time stamps
2016-02-22T13:40:28 shiprecv.mn2

2016-03-07T08:54:34 zformdis1.sc2  && same time stamps
2016-03-07T08:54:34 zformdis1.sc2
2016-03-03T16:12:00 zformdis1.SCT
2016-03-03T16:12:00 zformdis1.SCT
2016-03-04T12:31:20 zformdis1.scx
2016-03-04T12:31:20 zformdis1.scx

**Comment by mikepotjer** [comment] 2016-04-13 01:49
Thanks for the report, Eddie.  The class does a case-insensitive search when determining whether to add an item to the timestamp list, so I don't see case as a reason for the duplicates.  My hunch is that possibly 2 sides of a merge operation combined some results, rather than selecting one side or the other.  Looking at your commit history might indicate if that could be the case.  Regardless of the cause, I agree that the tool should check for and eliminate duplicates.

I appreciate your detailed analysis, and I agree with your conclusion that the duplicates were causing the timestamps to be reverted on your files.  Hopefully I can put out a fix for this soon.

Thanks as always for helping to make this a better tool,
Mike

**Closed as completed** 2016-07-23 22:49 UTC

**Comment by mikepotjer** [comment] 2016-07-23 22:57
Fixed by commit 281317c619c6b6adae9cd4b9396cc78703de884b.
Fix merged into master by commit 86f40158ab5accc25509634354b246451fd317dc.
